import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    BETTER_AUTH_SECRET: z.string().min(1),
    BETTER_AUTH_URL: z.string().url().optional(),
    CORS_ALLOWED_ORIGINS: z.string().optional(),
    VERCEL_URL: z.string().optional(),
    ADMIN_EMAIL: z.string().email().optional(),
    ADMIN_PASSWORD: z.string().min(1).optional(),
    ADMIN_NAME: z.string().min(1).optional(),
    ADVERTISER_EMAIL: z.string().email().optional(),
    ADVERTISER_PASSWORD: z.string().min(1).optional(),
    ADVERTISER_NAME: z.string().min(1).optional(),
    EVERFLOW_API_KEY: z.string().min(1).optional(),
    EVERFLOW_API_BASE_URL: z.string().url().optional(),
    EVERFLOW_API_REGION: z
      .enum(["api.eflow.team", "api-eu.eflow.team"])
      .optional(),
    EVERFLOW_NETWORK_ID: z.string().optional(),
    CRON_SECRET: z.string().min(1).optional(),
    ALERT_WEBHOOK_URL: z.string().url().optional(),
    BLOB_READ_WRITE_TOKEN: z.string().min(1).optional(),
    PYTHON_SERVICE_URL: z.string().url().optional(),
    GRAMMAR_AI_URL: z.string().url().optional(),
    TELEGRAM_BOT_TOKEN: z.string().min(1).optional(),
    UPSTASH_REDIS_REST_URL: z.string().url().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_BETTER_AUTH_URL: z.string().url().optional(),
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
    NEXT_PUBLIC_BLOB_URL: z.string().url().optional(),
    NEXT_PUBLIC_TELEGRAM_BOT_URL: z.string().url().optional(),
    AWS_ACCESS_KEY_ID: z.string().min(1).optional(),
    AWS_SECRET_ACCESS_KEY: z.string().min(1).optional(),
    AWS_REGION: z.string().min(1).optional(),
    AWS_SES_FROM_EMAIL: z.string().email().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
    CORS_ALLOWED_ORIGINS: process.env.CORS_ALLOWED_ORIGINS,
    VERCEL_URL: process.env.VERCEL_URL,
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
    ADMIN_NAME: process.env.ADMIN_NAME,
    ADVERTISER_EMAIL: process.env.ADVERTISER_EMAIL,
    ADVERTISER_PASSWORD: process.env.ADVERTISER_PASSWORD,
    ADVERTISER_NAME: process.env.ADVERTISER_NAME,
    EVERFLOW_API_KEY: process.env.EVERFLOW_API_KEY,
    EVERFLOW_API_BASE_URL: process.env.EVERFLOW_API_BASE_URL,
    EVERFLOW_API_REGION: process.env.EVERFLOW_API_REGION,
    EVERFLOW_NETWORK_ID: process.env.EVERFLOW_NETWORK_ID,
    CRON_SECRET: process.env.CRON_SECRET,
    ALERT_WEBHOOK_URL: process.env.ALERT_WEBHOOK_URL,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    PYTHON_SERVICE_URL: process.env.PYTHON_SERVICE_URL,
    GRAMMAR_AI_URL: process.env.GRAMMAR_AI_URL,
    TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    NEXT_PUBLIC_BETTER_AUTH_URL: process.env.NEXT_PUBLIC_BETTER_AUTH_URL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_BLOB_URL: process.env.NEXT_PUBLIC_BLOB_URL,
    NEXT_PUBLIC_TELEGRAM_BOT_URL: process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    AWS_REGION: process.env.AWS_REGION,
    AWS_SES_FROM_EMAIL: process.env.AWS_SES_FROM_EMAIL,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
