import type { Advertiser } from "../types/admin.types";

export const manageAdvertisers: Advertiser[] = [
  {
    id: "ADV-1001",
    advertiserName: "TechVision Marketing Solutions",
    advPlatform: "Cake",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "ADV-1002",
    advertiserName: "Global Reach Media Group",
    advPlatform: "HasOffers",
    createdMethod: "Manually",
    status: "Active",
  },
  {
    id: "ADV-1003",
    advertiserName: "Digital Performance Network",
    advPlatform: "Tune",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "ADV-1004",
    advertiserName: "Premier Affiliate Partners",
    advPlatform: "Cake",
    createdMethod: "Manually",
    status: "Inactive",
  },
  {
    id: "ADV-1005",
    advertiserName: "MaxConvert Digital",
    advPlatform: "Impact",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "ADV-1006",
    advertiserName: "SkyLine Advertising Agency",
    advPlatform: "HasOffers",
    createdMethod: "Manually",
    status: "Active",
  },
  {
    id: "ADV-1007",
    advertiserName: "Pinnacle Performance Marketing",
    advPlatform: "Everflow",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "ADV-1008",
    advertiserName: "Velocity Media Partners",
    advPlatform: "Cake",
    createdMethod: "Manually",
    status: "Inactive",
  },
  {
    id: "ADV-1009",
    advertiserName: "Quantum Digital Solutions",
    advPlatform: "Tune",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "ADV-1010",
    advertiserName: "Apex Marketing Collective",
    advPlatform: "Impact",
    createdMethod: "Manually",
    status: "Active",
  },
  {
    id: "ADV-1011",
    advertiserName: "Fusion Performance Group",
    advPlatform: "Cake",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "ADV-1012",
    advertiserName: "Horizon Direct Marketing",
    advPlatform: "HasOffers",
    createdMethod: "Manually",
    status: "Inactive",
  },
  {
    id: "ADV-1013",
    advertiserName: "NextGen Advertising Network",
    advPlatform: "Everflow",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "ADV-1014",
    advertiserName: "Catalyst Media Enterprises",
    advPlatform: "Tune",
    createdMethod: "Manually",
    status: "Active",
  },
  {
    id: "ADV-1015",
    advertiserName: "Summit Affiliate Networks",
    advPlatform: "Impact",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "ADV-1016",
    advertiserName: "Precision Marketing Group",
    advPlatform: "Cake",
    createdMethod: "Manually",
    status: "Inactive",
  },
  {
    id: "ADV-1017",
    advertiserName: "Elite Performance Solutions",
    advPlatform: "HasOffers",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "ADV-1018",
    advertiserName: "Strategic Digital Partners",
    advPlatform: "Everflow",
    createdMethod: "Manually",
    status: "Active",
  },
];
