import type { Publisher } from "../types/admin.types";

export const managePublishers: Publisher[] = [
  {
    id: "PUB-2001",
    publisherName: "MediaMax Publishing Network",
    pubPlatform: "Cake",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "PUB-2002",
    publisherName: "Digital Content Alliance",
    pubPlatform: "HasOffers",
    createdMethod: "Manually",
    status: "Active",
  },
  {
    id: "PUB-2003",
    publisherName: "Prime Traffic Solutions",
    pubPlatform: "Tune",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "PUB-2004",
    publisherName: "Elite Publisher Group",
    pubPlatform: "Impact",
    createdMethod: "Manually",
    status: "Inactive",
  },
  {
    id: "PUB-2005",
    publisherName: "Velocity Digital Media",
    pubPlatform: "Cake",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "PUB-2006",
    publisherName: "NextLevel Publishing Hub",
    pubPlatform: "Everflow",
    createdMethod: "Manually",
    status: "Active",
  },
  {
    id: "PUB-2007",
    publisherName: "Apex Content Network",
    pubPlatform: "HasOffers",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "PUB-2008",
    publisherName: "Strategic Media Partners",
    pubPlatform: "Tune",
    createdMethod: "Manually",
    status: "Inactive",
  },
  {
    id: "PUB-2009",
    publisherName: "Fusion Publishing Collective",
    pubPlatform: "Cake",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "PUB-2010",
    publisherName: "Global Traffic Exchange",
    pubPlatform: "Impact",
    createdMethod: "Manually",
    status: "Active",
  },
  {
    id: "PUB-2011",
    publisherName: "Pinnacle Content Solutions",
    pubPlatform: "Everflow",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "PUB-2012",
    publisherName: "Summit Digital Publishers",
    pubPlatform: "HasOffers",
    createdMethod: "Manually",
    status: "Inactive",
  },
  {
    id: "PUB-2013",
    publisherName: "Quantum Media Network",
    pubPlatform: "Cake",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "PUB-2014",
    publisherName: "Horizon Publishing Group",
    pubPlatform: "Tune",
    createdMethod: "Manually",
    status: "Active",
  },
  {
    id: "PUB-2015",
    publisherName: "Premier Traffic Network",
    pubPlatform: "Impact",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "PUB-2016",
    publisherName: "Catalyst Content Partners",
    pubPlatform: "Everflow",
    createdMethod: "Manually",
    status: "Inactive",
  },
  {
    id: "PUB-2017",
    publisherName: "Dynamic Publishing Solutions",
    pubPlatform: "HasOffers",
    createdMethod: "API",
    status: "Active",
  },
  {
    id: "PUB-2018",
    publisherName: "Precision Media Collective",
    pubPlatform: "Cake",
    createdMethod: "Manually",
    status: "Active",
  },
];
