/**
 * TODO: BACKEND - Remove Mock Data
 *
 * This file contains MOCK DATA for advertiser responses (development/testing only).
 *
 * Action Items:
 * 1. Remove this entire file once backend APIs are integrated
 * 2. All advertiser response data should come from advertiser_responses table
 * 3. Update imports in request.service.ts to remove references to this file
 * 4. Ensure no production code depends on this mock data
 *
 * Note: Keep this file during development for frontend testing
 */

import type { Request } from "../types/admin.types";

export const advertiserResponses: Request[] = [
  {
    id: "resp-1",
    date: "22nd December 2024",
    advertiserName: "Amazon Affiliates",
    affiliateId: "AFF-8901",
    priority: "High Priority",
    offerId: "5001",
    offerName:
      "RETAIL - E-COMMERCE - [Holiday Special] - [US/CA] - [Email/Display] - [All Days]",
    clientId: "CLI-1001",
    clientName: "Digital Media Group",
    creativeType: "Email",
    creativeCount: 3,
    fromLinesCount: 2,
    subjectLinesCount: 3,
    status: "new",
    approvalStage: "advertiser",
    parentRequestId: "req-1",
  },
  {
    id: "resp-2",
    date: "21st December 2024",
    advertiserName: "Google Marketing",
    affiliateId: "AFF-8902",
    priority: "High Priority",
    offerId: "5014",
    offerName:
      "TECH - CLOUD SERVICES - [Enterprise Solutions] - [Global] - [Email/Display] - [Business Hours]",
    clientId: "CLI-1014",
    clientName: "Cloud Publishers Network",
    creativeType: "Email",
    creativeCount: 4,
    fromLinesCount: 3,
    subjectLinesCount: 4,
    status: "new",
    approvalStage: "advertiser",
    parentRequestId: "req-2",
  },
  {
    id: "resp-3",
    date: "20th December 2024",
    advertiserName: "Microsoft Advertising",
    affiliateId: "AFF-8903",
    priority: "Medium Priority",
    offerId: "5015",
    offerName:
      "SOFTWARE - PRODUCTIVITY - [Office 365] - [US/CA/UK] - [Email] - [All Days]",
    clientId: "CLI-1015",
    clientName: "Productivity Media Group",
    creativeType: "Display",
    creativeCount: 5,
    fromLinesCount: 0,
    subjectLinesCount: 0,
    status: "approved",
    approvalStage: "advertiser",
    parentRequestId: "req-3",
  },
  {
    id: "resp-4",
    date: "19th December 2024",
    advertiserName: "Facebook Ads Network",
    affiliateId: "AFF-8904",
    priority: "High Priority",
    offerId: "5016",
    offerName:
      "SOCIAL - ADVERTISING - [Business Growth] - [Global] - [Social Media] - [All Days]",
    clientId: "CLI-1016",
    clientName: "Social Growth Partners",
    creativeType: "Social Media",
    creativeCount: 8,
    fromLinesCount: 0,
    subjectLinesCount: 0,
    status: "approved",
    approvalStage: "advertiser",
    parentRequestId: "req-4",
  },
  {
    id: "resp-5",
    date: "18th December 2024",
    advertiserName: "Apple Developer Network",
    affiliateId: "AFF-8908",
    priority: "Medium Priority",
    offerId: "5017",
    offerName:
      "TECH - APP STORE - [Developer Program] - [Global] - [Email/Mobile] - [Business Hours]",
    clientId: "CLI-1017",
    clientName: "App Developer Media",
    creativeType: "Mobile",
    creativeCount: 6,
    fromLinesCount: 0,
    subjectLinesCount: 0,
    status: "rejected",
    approvalStage: "advertiser",
    parentRequestId: "req-8",
  },
  {
    id: "resp-6",
    date: "17th December 2024",
    advertiserName: "Salesforce Marketing",
    affiliateId: "AFF-8907",
    priority: "High Priority",
    offerId: "5018",
    offerName:
      "CRM - SALES CLOUD - [SMB Package] - [US/EU] - [Email/LinkedIn] - [Mon-Fri Only]",
    clientId: "CLI-1018",
    clientName: "SMB Solutions Media",
    creativeType: "Email",
    creativeCount: 3,
    fromLinesCount: 2,
    subjectLinesCount: 3,
    status: "rejected",
    approvalStage: "advertiser",
    parentRequestId: "req-7",
  },
  {
    id: "resp-7",
    date: "16th December 2024",
    advertiserName: "Netflix Advertising",
    affiliateId: "AFF-8909",
    priority: "Medium Priority",
    offerId: "5019",
    offerName:
      "STREAMING - CONTENT - [Premium Tier] - [US/CA/UK] - [Video/Display] - [All Days]",
    clientId: "CLI-1019",
    clientName: "Entertainment Publishers Ltd",
    creativeType: "Video",
    creativeCount: 7,
    fromLinesCount: 0,
    subjectLinesCount: 0,
    status: "sent-back",
    approvalStage: "advertiser",
    parentRequestId: "req-9",
  },
  {
    id: "resp-8",
    date: "15th December 2024",
    advertiserName: "Adobe Creative Cloud",
    affiliateId: "AFF-8906",
    priority: "High Priority",
    offerId: "5020",
    offerName:
      "DESIGN - CREATIVE SUITE - [Professional Plan] - [Global] - [Email] - [Business Hours]",
    clientId: "CLI-1020",
    clientName: "Creative Pro Publishers",
    creativeType: "Email",
    creativeCount: 4,
    fromLinesCount: 3,
    subjectLinesCount: 4,
    status: "new",
    approvalStage: "advertiser",
    parentRequestId: "req-6",
  },
  {
    id: "resp-9",
    date: "14th December 2024",
    advertiserName: "Spotify for Brands",
    affiliateId: "AFF-8910",
    priority: "Medium Priority",
    offerId: "5021",
    offerName:
      "MUSIC - PREMIUM - [Family Plan] - [Global] - [Audio/Display] - [All Days]",
    clientId: "CLI-1021",
    clientName: "Audio Media Network",
    creativeType: "Audio",
    creativeCount: 5,
    fromLinesCount: 0,
    subjectLinesCount: 0,
    status: "approved",
    approvalStage: "advertiser",
    parentRequestId: "req-10",
  },
  {
    id: "resp-10",
    date: "13th December 2024",
    advertiserName: "Booking.com Partners",
    affiliateId: "AFF-8905",
    priority: "High Priority",
    offerId: "5022",
    offerName:
      "TRAVEL - HOTEL DEALS - [Winter Season] - [Global] - [Email/Display] - [All Days]",
    clientId: "CLI-1022",
    clientName: "Travel Deals Publishers",
    creativeType: "Email",
    creativeCount: 6,
    fromLinesCount: 4,
    subjectLinesCount: 5,
    status: "sent-back",
    approvalStage: "advertiser",
    parentRequestId: "req-5",
  },
];
